args:
  latent_channels: 16
  mode: inference
  load: ckpts_5b/sf_v3_pathB_cont500_lr1e6_iter500
  batch_size: 1
  sampling_image_size: [480, 720]
  sampling_num_frames: 13
  sampling_fps: 8
  fp16: false
  bf16: true
  force_inference: true
